// Code generated by 'yaegi extract github.com/Gandalf-Le-Dev/ebiten-yaegi/engine'. DO NOT EDIT.

package symbols

import (
	"github.com/Gandalf-Le-Dev/ebiten-yaegi/engine"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/Gandalf-Le-Dev/ebiten-yaegi/engine/engine"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BallSize":      reflect.ValueOf(constant.MakeFromLiteral("10", token.INT, 0)),
		"GetScreenSize": reflect.ValueOf(engine.GetScreenSize),
		"InitEngine":    reflect.ValueOf(engine.InitEngine),
		"PaddleHeight":  reflect.ValueOf(constant.MakeFromLiteral("60", token.INT, 0)),
		"PaddleWidth":   reflect.ValueOf(constant.MakeFromLiteral("10", token.INT, 0)),
		"ScreenHeight":  reflect.ValueOf(constant.MakeFromLiteral("480", token.INT, 0)),
		"ScreenWidth":   reflect.ValueOf(constant.MakeFromLiteral("640", token.INT, 0)),

		// type definitions
		"GameStruct": reflect.ValueOf((*engine.GameStruct)(nil)),
	}
}
