// Code generated by 'yaegi extract github.com/hajimehoshi/ebiten/v2/ebitenutil'. DO NOT EDIT.

package symbols

import (
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
	"reflect"
)

func init() {
	Symbols["github.com/hajimehoshi/ebiten/v2/ebitenutil/ebitenutil"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DebugPrint":             reflect.ValueOf(ebitenutil.DebugPrint),
		"DebugPrintAt":           reflect.ValueOf(ebitenutil.DebugPrintAt),
		"DrawCircle":             reflect.ValueOf(ebitenutil.DrawCircle),
		"DrawLine":               reflect.ValueOf(ebitenutil.DrawLine),
		"DrawRect":               reflect.ValueOf(ebitenutil.DrawRect),
		"NewImageFromFile":       reflect.ValueOf(ebitenutil.NewImageFromFile),
		"NewImageFromFileSystem": reflect.ValueOf(ebitenutil.NewImageFromFileSystem),
		"NewImageFromReader":     reflect.ValueOf(ebitenutil.NewImageFromReader),
		"NewImageFromURL":        reflect.ValueOf(ebitenutil.NewImageFromURL),
		"OpenFile":               reflect.ValueOf(ebitenutil.OpenFile),

		// type definitions
		"ReadSeekCloser": reflect.ValueOf((*ebitenutil.ReadSeekCloser)(nil)),

		// interface wrapper definitions
		"_ReadSeekCloser": reflect.ValueOf((*_github_com_hajimehoshi_ebiten_v2_ebitenutil_ReadSeekCloser)(nil)),
	}
}

// _github_com_hajimehoshi_ebiten_v2_ebitenutil_ReadSeekCloser is an interface wrapper for ReadSeekCloser type
type _github_com_hajimehoshi_ebiten_v2_ebitenutil_ReadSeekCloser struct {
	IValue interface{}
	WClose func() error
	WRead  func(p []byte) (n int, err error)
	WSeek  func(offset int64, whence int) (int64, error)
}

func (W _github_com_hajimehoshi_ebiten_v2_ebitenutil_ReadSeekCloser) Close() error {
	return W.WClose()
}
func (W _github_com_hajimehoshi_ebiten_v2_ebitenutil_ReadSeekCloser) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_hajimehoshi_ebiten_v2_ebitenutil_ReadSeekCloser) Seek(offset int64, whence int) (int64, error) {
	return W.WSeek(offset, whence)
}
