// Code generated by 'yaegi extract golang.org/x/exp/rand'. DO NOT EDIT.

package symbols

import (
	"golang.org/x/exp/rand"
	"reflect"
)

func init() {
	Symbols["golang.org/x/exp/rand/rand"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ExpFloat64":  reflect.ValueOf(rand.ExpFloat64),
		"Float32":     reflect.ValueOf(rand.Float32),
		"Float64":     reflect.ValueOf(rand.Float64),
		"Int":         reflect.ValueOf(rand.Int),
		"Int31":       reflect.ValueOf(rand.Int31),
		"Int31n":      reflect.ValueOf(rand.Int31n),
		"Int63":       reflect.ValueOf(rand.Int63),
		"Int63n":      reflect.ValueOf(rand.Int63n),
		"Intn":        reflect.ValueOf(rand.Intn),
		"New":         reflect.ValueOf(rand.New),
		"NewSource":   reflect.ValueOf(rand.NewSource),
		"NewZipf":     reflect.ValueOf(rand.NewZipf),
		"NormFloat64": reflect.ValueOf(rand.NormFloat64),
		"Perm":        reflect.ValueOf(rand.Perm),
		"Read":        reflect.ValueOf(rand.Read),
		"Seed":        reflect.ValueOf(rand.Seed),
		"Shuffle":     reflect.ValueOf(rand.Shuffle),
		"Uint32":      reflect.ValueOf(rand.Uint32),
		"Uint64":      reflect.ValueOf(rand.Uint64),

		// type definitions
		"LockedSource": reflect.ValueOf((*rand.LockedSource)(nil)),
		"PCGSource":    reflect.ValueOf((*rand.PCGSource)(nil)),
		"Rand":         reflect.ValueOf((*rand.Rand)(nil)),
		"Source":       reflect.ValueOf((*rand.Source)(nil)),
		"Zipf":         reflect.ValueOf((*rand.Zipf)(nil)),

		// interface wrapper definitions
		"_Source": reflect.ValueOf((*_golang_org_x_exp_rand_Source)(nil)),
	}
}

// _golang_org_x_exp_rand_Source is an interface wrapper for Source type
type _golang_org_x_exp_rand_Source struct {
	IValue  interface{}
	WSeed   func(seed uint64)
	WUint64 func() uint64
}

func (W _golang_org_x_exp_rand_Source) Seed(seed uint64) {
	W.WSeed(seed)
}
func (W _golang_org_x_exp_rand_Source) Uint64() uint64 {
	return W.WUint64()
}
